tasks:
  - name: install google-cloud-sdk
    init: |
      curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      tar -xvf google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      ./google-cloud-sdk/install.sh
      rm google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      . ~/.bashrc # exec bash
      gcloud auth login
      read -p "Enter Your GCP Project ID: " GCP_ID
      gcloud config set project $GCP_ID
      gcloud auth application-default login
      gp sync-done gc-sdk
  - name: Install neptune, pip, jupyter 
    init: |
      gp sync-await gc-sdk
      pip install neptune-client lightgbm neptune-lightgbm
      pip install -r requirements.txt
      jupyter notebook --ip=*
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    onOpen: open-preview