tasks:
  - name: install google-cloud-sdk
    init: |
      curl -O https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      tar -xvf google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      ./google-cloud-sdk/install.sh
      rm google-cloud-sdk-358.0.0-linux-x86_64.tar.gz
      . ~/.bashrc # exec bash
      gcloud auth login
      read -p "Enter Your GCP Project ID: " GCP_ID
      gcloud config set project $GCP_ID
      export GCLOUD_PROJECT=$GCP_ID
      gcloud auth application-default login

      pip install neptune-client lightgbm neptune-lightgbm neptune-notebooks
      pip install -r requirements.txt # pip freeze > requirements.txt
      jupyter notebook --generate-config
      echo -e '\nc.NotebookApp.contents_manager_class = "jupytext.TextFileContentsManager"' >> ~/.jupyter/jupyter_notebook_config.py
      echo -e '\nc.ContentsManager.default_jupytext_formats = "ipynb,py"' >> ~/.jupyter/jupyter_notebook_config.py
      jupyter nbextension enable --py neptune-notebooks
      gp sync-done gc-sdk
      jupyter notebook --ip=*
  - name: new shell
    init: |
      gp sync-await gc-sdk
    openMode: split-right

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8888
    onOpen: open-preview